name: movie_analyst

services:

  db:
    container_name: movie_analyst_db
    image: 'mysql:9.3.0-oracle'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_db
    volumes:
      - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend

  api:
    container_name: movie_analyst_api
    restart: unless-stopped
    build:
      context: movie-analyst-api
      dockerfile: Dockerfile
    ports:
      - '8000:8000' # host:container
    environment:
      - DB_HOST=movie_analyst_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=movie_db
    depends_on:
      - db
    networks:
      - backend
      - frontend

  ui:
    container_name: movie_analyst_ui
    restart: unless-stopped
    build:
      context: movie-analyst-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://movie_analyst_api:8000
    depends_on:
      - api
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge